version: "3.8"

services:

  mongo:
    container_name: fastapi_project_db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE_NAME: fastapi_project
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./mongo-volume:/data/db
    ports:
      - 27017:27017
  mongo-express:
    container_name: mongo_express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo/

  app:
    container_name: fastapi_project
    build: .
    command: bash -c "uvicorn fastapi_app.app:app --host 0.0.0.0 --port 8000 --reload"
#     command: bash -c "python3 main.py"
    volumes:
      - .:/fastapi_project_db
    ports:
      - 8000:8000
    depends_on:
      - mongo
    restart: always